import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { propertiesService } from '../../../services/properties';
import { RootState } from '../../../stores';

import { 
  IServiceRequest, 
  IPropertyShow, 
  IServiceError 
} from '../../../types';

export interface IPropertiesShowServiceRequest extends IServiceRequest {
  data?: IPropertyShow | IServiceError;
}

const initialState: IPropertiesShowServiceRequest = {
  status: 'idle',
};

export const propertiesShowThunk = createAsyncThunk(
  'properties/show',
  async (code: string) => {
    const response = await propertiesService.show(code);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const propertiesShowSlice = createSlice({
  name: 'properties-show',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(propertiesShowThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(propertiesShowThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data as IPropertyShow;
      })
      .addCase(propertiesShowThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const selectPropertiesShowReducer = (state: RootState) => state.propertiesShowReducer;

export default propertiesShowSlice.reducer;
