import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { propertiesPhotosService } from '../../../../services/properties';
import { RootState } from '../../../../stores';

import { IServiceRequest, IPaginateDefault, IServiceError, IPhotoUpdatePositionsPayload, IServiceRequestStatus, IPropertyShow } from '../../../../types';

export interface IPropertiesPhotosUpdatePositionsServiceRequest extends IServiceRequest {
  data?: IPaginateDefault | IServiceError | IPropertyShow
}

const initialState: IPropertiesPhotosUpdatePositionsServiceRequest = {
  name: 'propertiesPhotosUpdatePositionsReducer',
  status: 'idle',
};

interface IPropertiesPhotosUpdatePositionsThunk {
  code: string;
  data: IPhotoUpdatePositionsPayload[];
}

export const propertiesPhotosUpdatePositionsThunk = createAsyncThunk(
  'properties/photos-update-positions',
  async ({ code, data }: IPropertiesPhotosUpdatePositionsThunk) => {
    const response = await propertiesPhotosService.updatePositions(code, data);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const propertiesPhotosUpdatePositionsSlice = createSlice({
  name: 'properties-photos-update-positions',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setStatus: (state, actions: PayloadAction<IServiceRequestStatus>) => {
      state.status = actions.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(propertiesPhotosUpdatePositionsThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(propertiesPhotosUpdatePositionsThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data;
      })
      .addCase(propertiesPhotosUpdatePositionsThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const { setStatus } = propertiesPhotosUpdatePositionsSlice.actions;

export const selectPropertiesPhotosUpdatePositionsReducer = (state: RootState) => state.propertiesPhotosUpdatePositionsReducer;

export default propertiesPhotosUpdatePositionsSlice.reducer;
