import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '../../../stores';

import { propertiesAgenciesService } from '../../../services/propertiesAgencies';
import { IPaginationServiceThunk, IServiceRequest } from '../../../types';

const initialState: IServiceRequest = {
  name: 'propertiesAgenciesListReducer',
  status: 'idle',
};

export const propertiesAgenciesServiceThunk = createAsyncThunk(
  'propertiesAgencies/list',
  async ({ page }: IPaginationServiceThunk) => {
    const response = await propertiesAgenciesService.list({ page });
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const propertiesAgenciesListSlice = createSlice({
  name: 'propertiesAgencies-list',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Start List Action */
      .addCase(propertiesAgenciesServiceThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(propertiesAgenciesServiceThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data;
      })
      .addCase(propertiesAgenciesServiceThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as object;
      });
  },
});

// export const {} = propertiesAgenciesListSlice.actions;

export const selectPropertiesAgenciesListReducer = (state: RootState) => state.propertiesAgenciesListReducer;

export default propertiesAgenciesListSlice.reducer;
