import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { citiesService } from '../../../services/cities';
import { RootState } from '../../../stores';

import { 
  IServiceRequest, 
  IServiceError,
  ICitiesDataSearchResult
} from '../../../types';

export interface ICitiesSearchServiceRequest extends IServiceRequest {
  data?: ICitiesDataSearchResult | IServiceError;
}

const initialState: ICitiesSearchServiceRequest = {
  name: 'citiesSearchReducer',
  status: 'idle',
};

export const citiesSearchThunk = createAsyncThunk(
  'cities/search',
  async (search: string) => {
    const response = await citiesService.search(search);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const citiesSearchSlice = createSlice({
  name: 'citiesSearchReducer',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(citiesSearchThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(citiesSearchThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data as ICitiesDataSearchResult;
      })
      .addCase(citiesSearchThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const selectCitiesSearchReducer = (state: RootState) => state.citiesSearchReducer;

export default citiesSearchSlice.reducer;
