import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { ISubscriptionPaymentIntentServiceRequest, ISubscriptionPaymentServiceRequest, subscriptionService } from '../../services/subscription';

import { IServiceRequest } from '../../types';
import { normalizeError } from '../../helpers';

export interface IPayment {
  id?: number;
  subscription_id: number;
  payment_category_id: number;
  client_id: number;
  stripe_code_payment: string;
  amount: number | null;
  description: string;
  quantity: number | null;
  reference_date: Date | null;
  paid_at: Date | null;
  created_at?: Date;
  updated_at?: Date;
}

export interface ISubscriptionState extends IServiceRequest {
  paymentIntentService: IServiceRequest;
  paymentConfirmService: IServiceRequest
  availablePaymentsService: IServiceRequest
}

const initialState: ISubscriptionState = {
  name: 'subscriptionReducer',
  status: 'idle',
  paymentIntentService: {
    name: 'subscriptionReducer/paymentIntentService',
    error: null,
    data: {},
    status: 'idle',
  },
  paymentConfirmService: {
    name: 'subscriptionReducer/paymentConfirmService',
    error: null,
    data: {},
    status: 'idle',
  },
  availablePaymentsService: {
    name: 'subscriptionReducer/availablePaymentsService',
    error: null,
    data: {},
    status: 'idle',
  }
};

export const paymentIntentServiceThunk = createAsyncThunk(
  'subscription/paymentIntent',
  async (data: ISubscriptionPaymentIntentServiceRequest) => {
    const response = await subscriptionService.paymentIntent(data);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const paymentConfirmServiceThunk = createAsyncThunk(
  'subscription/payment',
  async ({ stripe, cardElement, clientSecret, billingDetails, paymentIntentId, paymentAvailableId }: ISubscriptionPaymentServiceRequest) => {
    let status: 'success' | 'pending' = 'pending';
    let error = '';

    /**
     * Call PUT /api/payments/:paymentAvailableId to set paymentIntentId in the payment register.
    */
    const paymentAvailableIntentResponse = await subscriptionService.setPaymentAvailableIntent(String(paymentAvailableId), { paymentIntentId });

    const { data: paymentAvailableIntent } = paymentAvailableIntentResponse;

    console.log('[REDUCER] paymentAvailableIntent', paymentAvailableIntent);
    

    /**
     * TODO: To treat that flow... in Subscription page.
    */
    if (paymentAvailableIntent?.data?.stripe_code_payment !== paymentIntentId) {
      error = 'Algo de errado ao sincronizar a intenção de pagamento da Stripe com a API';
      return { status, error }; // Status 'pending'.
    }

    // IF PUT /api/payments/:paymentAvailableId returned success call Stripe confirmCardPayment
    const response = await stripe?.confirmCardPayment(clientSecret || '', {
      payment_method: {
        card: cardElement || { token: '' },
        billing_details: {
          name: billingDetails?.name,
        },
      },
    }) || { error: '', paymentIntent: '' };

    /**
     *  Call PUT /api/payments/:paymentAvailableId to set paid_at date.
     */
    if (
      response?.paymentIntent?.id === paymentIntentId
      && response?.paymentIntent?.status === 'succeeded'
    ) {
      // IF PUT /api/payments/:paymentAvailableId returned success set status success to UI notify the user.
      const paymentAvailableIntentConfirmResponse = await subscriptionService.setPaymentAvailableIntentConfirm(String(paymentAvailableId), { paymentIntentId });

      const { data: paymentAvailableIntentConfirm } = paymentAvailableIntentConfirmResponse;

      if (paymentAvailableIntentConfirm?.data?.paid_at && paymentAvailableIntentConfirm?.data?.stripe_code_payment === paymentIntentId)
        status = 'success';
      else
        error = 'Algo de errado ao finalizar o pagamento Stripe > API.';
    } else {
      error = 'Algo de errado ao confirmar o pagamento com a Stripe';
    }

    /**
     * TODO:
     *    
     *    User must be notify about the status, friendly!
     *    But the Imob Admin Clients should track that "pending" payments to fix, because String processed tha payment, customer paid!
    */

    return { ...response, error };
  }
);

export const availablePaymentsServiceThunk = createAsyncThunk(
  'subscription/availablePayments',
  async (_, { rejectWithValue }) => {
    try {
      const response = await subscriptionService.availablePayments();
      // The value we return becomes the `fulfilled` action payload
      return response;
    } catch (error) {
      return rejectWithValue(normalizeError(error));
    }
  }
);

export const subscriptionSlice = createSlice({
  name: 'subscription',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Intent Payment */
      .addCase(paymentIntentServiceThunk.pending, (state) => {
        state.paymentIntentService.status = 'loading';
      })
      .addCase(paymentIntentServiceThunk.fulfilled, (state, action) => {
        state.paymentIntentService.status = 'success';
        state.paymentIntentService.data = action.payload.data;
      })
      .addCase(paymentIntentServiceThunk.rejected, (state, action) => {
        state.paymentIntentService.status = 'failed';
        state.paymentIntentService.data = [];
        state.paymentIntentService.error = action.payload;
      })
      /** Confirm Payment */
      .addCase(paymentConfirmServiceThunk.pending, (state) => {
        state.paymentConfirmService.status = 'loading';
      })
      .addCase(paymentConfirmServiceThunk.fulfilled, (state, action) => {
        const dataResponse = action.payload as any;

        if (dataResponse.error) state.paymentConfirmService.status = 'failed';
        else state.paymentConfirmService.status = 'success';

        state.paymentIntentService.data = [];
        state.paymentConfirmService.data = action.payload;
      })
      .addCase(paymentConfirmServiceThunk.rejected, (state, action) => {
        state.paymentConfirmService.status = 'failed';
        state.paymentConfirmService.data = [];
        state.paymentConfirmService.error = action.payload;
      })
      /** Available Payments */
      .addCase(availablePaymentsServiceThunk.pending, (state) => {
        state.availablePaymentsService.status = 'loading';
      })
      .addCase(availablePaymentsServiceThunk.fulfilled, (state, action) => {
        state.availablePaymentsService.status = 'success';
        state.availablePaymentsService.data = action.payload.data.data;
      })
      .addCase(availablePaymentsServiceThunk.rejected, (state, action) => {
        state.availablePaymentsService.status = 'failed';
        state.availablePaymentsService.data = [];
        state.availablePaymentsService.error = action.payload;
      });
  },
});

export default subscriptionSlice.reducer;
