import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { propertiesService } from '../../../../services/properties';
import { RootState } from '../../../../stores';

import { IServiceRequest, IPaginateDefault, IServiceError, IServiceSuccess } from '../../../../types';

export interface IPropertiesPhotosServiceRequest extends IServiceRequest {
  data?: IPaginateDefault | IServiceError | IServiceSuccess
}

const initialState: IPropertiesPhotosServiceRequest = {
  name: 'propertiesPhotosReducer',
  status: 'idle',
};

export const propertiesPhotosThunk = createAsyncThunk(
  'properties/photos',
  async (code: string) => {
    const response = await propertiesService.photos(code);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const propertiesPhotosSlice = createSlice({
  name: 'properties-photos',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(propertiesPhotosThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(propertiesPhotosThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data;
      })
      .addCase(propertiesPhotosThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const selectPropertiesPhotosReducer = (state: RootState) => state.propertiesPhotosReducer;

export default propertiesPhotosSlice.reducer;
