import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { propertiesService } from '../../../services/properties';
import { RootState } from '../../../stores';

import { resolvePropertyStorePayload, statusCodeIs } from '../../../helpers';

import { 
  IServiceRequest, 
  IPropertyShow, 
  IServiceError,
  IServiceFieldsRequired,
  IPropertyData,
  IServiceRequestStatus,
} from '../../../types';

export interface IPropertiesStoreServiceRequest extends IServiceRequest {
  data?: IPropertyShow | IServiceFieldsRequired | IServiceError;
}

const initialState: IPropertiesStoreServiceRequest = {
  name: 'propertiesStoreReducer',
  status: 'idle',
};

export const propertiesStoreThunk = createAsyncThunk(
  'properties/store',
  async (dataStore: IPropertyData) => {
    const response = await propertiesService.store(resolvePropertyStorePayload(dataStore));
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const propertiesStoreSlice = createSlice({
  name: 'properties-store',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setStatus: (state, action: PayloadAction<IServiceRequestStatus>) => {
      state.status = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(propertiesStoreThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(propertiesStoreThunk.fulfilled, (state, action) => {
        if (statusCodeIs(action.payload.status) === 'success') state.status = 'success';
        if (statusCodeIs(action.payload.status) === 'error') state.status = 'failed';
        state.data = action.payload.data as IPropertyShow;
      })
      .addCase(propertiesStoreThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const { setStatus } = propertiesStoreSlice.actions;

export const selectPropertiesStoreReducer = (state: RootState) => state.propertiesStoreReducer;

export default propertiesStoreSlice.reducer;
