import { PayloadAction, createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { propertiesService } from '../../../services/properties';
import { RootState } from '../../../stores';

import { 
  IServiceRequest,
  IServiceError,
  IPropertyData,
  IServiceDataRequest,
} from '../../../types';

export interface IPropertySearchServiceRequest extends IServiceRequest {
  data?: IServiceDataRequest;
  propertySelected: IPropertyData[];
}

const initialState: IPropertySearchServiceRequest = {
  name: 'propertiesSearchReducer',
  status: 'idle',
  propertySelected: []
};

export const propertiesSearchThunk = createAsyncThunk(
  'properties/search',
  async (search: string) => {
    const response = await propertiesService.search(search);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const propertiesSearchSlice = createSlice({
  name: 'properties-search',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setSelectedProperties: (state, action: PayloadAction<IPropertyData[]>) => {
      console.log('DEBUG setSelectedProperties action.payload:', action.payload);
      
      state.propertySelected = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(propertiesSearchThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(propertiesSearchThunk.fulfilled, (state, action) => {
        state.status = 'success';
        console.log('DEBUG action.payload:', action.payload);
        state.data = action.payload.data as IServiceDataRequest;
      })
      .addCase(propertiesSearchThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const { setSelectedProperties } = propertiesSearchSlice.actions;

export const selectPropertiesSearchReducer = (state: RootState) => state.propertiesSearchReducer;

export default propertiesSearchSlice.reducer;
