import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { ownersService } from '../../../services/owners';
import { RootState } from '../../../stores';

import { 
  IServiceRequest, 
  IServiceError,
  IOwnerDataSearchResult,
  IOwnerData
} from '../../../types';

export interface IOwnerSearchServiceRequest extends IServiceRequest {
  data?: IOwnerDataSearchResult | IServiceError;
  ownerSelected: IOwnerData[];
}

const initialState: IOwnerSearchServiceRequest = {
  name: 'ownersSearchReducer',
  status: 'idle',
  ownerSelected: []
};

export const ownersSearchThunk = createAsyncThunk(
  'owners/search',
  async (search: string) => {
    const response = await ownersService.search(search);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const ownersSearchSlice = createSlice({
  name: 'owners-search',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setSelectedOwners: (state, action: PayloadAction<IOwnerData[]>) => {
      state.ownerSelected = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(ownersSearchThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(ownersSearchThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data as IOwnerDataSearchResult;
      })
      .addCase(ownersSearchThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const { setSelectedOwners } = ownersSearchSlice.actions;

export const selectOwnersSearchReducer = (state: RootState) => state.ownersSearchReducer;

export default ownersSearchSlice.reducer;
