import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { ownersService } from '../../../services/owners';
import { RootState } from '../../../stores';

import { resolveOwnerStorePayload, statusCodeIs } from '../../../helpers';

import { 
  IServiceRequest, 
  IOwnerShow,
  IServiceError,
  IServiceFieldsRequired,
  IOwnerData,
  IServiceRequestStatus,
} from '../../../types';

export interface IOwnerStoreServiceRequest extends IServiceRequest {
  data?: IOwnerShow | IServiceFieldsRequired | IServiceError;
}

const initialState: IOwnerStoreServiceRequest = {
  name: 'ownersStoreReducer',
  status: 'idle',
};

export const ownersStoreThunk = createAsyncThunk(
  'owners/store',
  async (dataStore: IOwnerData) => {
    const response = await ownersService.store(resolveOwnerStorePayload(dataStore));
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const ownersStoreSlice = createSlice({
  name: 'owners-store',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setStatus: (state, action: PayloadAction<IServiceRequestStatus>) => {
      state.status = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(ownersStoreThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(ownersStoreThunk.fulfilled, (state, action) => {
        if (statusCodeIs(action.payload.status) === 'success') state.status = 'success';
        if (statusCodeIs(action.payload.status) === 'error') state.status = 'failed';
        state.data = action.payload.data as IOwnerShow;
      })
      .addCase(ownersStoreThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const { setStatus } = ownersStoreSlice.actions;

export const selectOwnersStoreReducer = (state: RootState) => state.ownersStoreReducer;

export default ownersStoreSlice.reducer;
