import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { ownersService } from '../../../services/owners';
import { RootState } from '../../../stores';

import { resolveOwnerUpdatePayload, statusCodeIs } from '../../../helpers';

import { 
  IServiceRequest, 
  IOwnerShow,
  IServiceError,
  IOwnerServiceFieldsRequired,
  IOwnerData,
  IServiceRequestStatus,
} from '../../../types';

export interface IOwnerUpdateServiceRequest extends IServiceRequest {
  data?: IOwnerShow | IOwnerServiceFieldsRequired | IServiceError;
}

const initialState: IOwnerUpdateServiceRequest = {
  name: 'ownersUpdateReducer',
  status: 'idle',
};

export const ownersUpdateThunk = createAsyncThunk(
  'owners/update',
  async (dataUpdate: IOwnerData) => {
    const response = await ownersService.update(resolveOwnerUpdatePayload(dataUpdate));
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const ownersUpdateSlice = createSlice({
  name: 'owners-update',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setStatus: (state, action: PayloadAction<IServiceRequestStatus>) => {
      state.status = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(ownersUpdateThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(ownersUpdateThunk.fulfilled, (state, action) => {
        if (statusCodeIs(action.payload.status) === 'success') state.status = 'success';
        if (statusCodeIs(action.payload.status) === 'error') state.status = 'failed';
        state.data = action.payload.data as IOwnerShow;
      })
      .addCase(ownersUpdateThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const { setStatus } = ownersUpdateSlice.actions;

export const selectOwnersUpdateReducer = (state: RootState) => state.ownersUpdateReducer;

export default ownersUpdateSlice.reducer;
