import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { ownersService } from '../../../services/owners';
import { RootState } from '../../../stores';

import { 
  IServiceRequest, 
  IOwnerShow, 
  IServiceError 
} from '../../../types';

export interface IOwnersShowServiceRequest extends IServiceRequest {
  data?: IOwnerShow | IServiceError;
}

const initialState: IOwnersShowServiceRequest = {
  name: 'ownersShowReducer',
  status: 'idle',
};

export const ownersShowThunk = createAsyncThunk(
  'owner/show',
  async (id: string) => {
    const response = await ownersService.show(id);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const ownerShowSlice = createSlice({
  name: 'owner-show',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(ownersShowThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(ownersShowThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data as IOwnerShow;
      })
      .addCase(ownersShowThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const selectOwnersShowReducer = (state: RootState) => state.ownersShowReducer;

export default ownerShowSlice.reducer;
