import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { resolveNeighborhoodsStorePayload } from '../../../helpers';
import { neighborhoodsService } from '../../../services/neighborhoods';
import { RootState } from '../../../stores';

import { IServiceRequestTemp, IPaginationServiceThunk, INeighborhoodData, IServiceRequestStatus } from '../../../types';

const initialState: IServiceRequestTemp = {
  name: 'neighborhoodsListReducer',
  status: 'idle',
  crud: {
    create: {
      name: 'neighborhoodsCreateReducer',
      status: 'idle',
    },
    read: {
      name: 'neighborhoodsReadReducer',
      status: 'idle',
    },
    update: {
      name: 'neighborhoodsUpdateReducer',
      status: 'idle',
    },
    delete: {
      name: 'neighborhoodsDeleteReducer',
      status: 'idle',
    },
  }
};

export const neighborhoodsServiceThunk = createAsyncThunk(
  'neighborhoods/list',
  async ({ page }: IPaginationServiceThunk) => {
    const response = await neighborhoodsService.list({ page });
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const neighborhoodsStoreThunk = createAsyncThunk(
  'neighborhoods/store',
  async (dataStore: INeighborhoodData) => {
    const response = await neighborhoodsService.store(resolveNeighborhoodsStorePayload(dataStore), String(dataStore?.city_id));
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const neighborhoodsUpdateThunk = createAsyncThunk(
  'neighborhoods/update',
  async (dataStore: INeighborhoodData) => {
    const response = await neighborhoodsService.update(String(dataStore.id), resolveNeighborhoodsStorePayload(dataStore));
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const neighborhoodsDeleteThunk = createAsyncThunk(
  'neighborhoods/delete',
  async (dataUpdate: INeighborhoodData) => {
    const response = await neighborhoodsService.delete(String(dataUpdate.id));
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const neighborhoodsShowThunk = createAsyncThunk(
  'neighborhoods/show',
  async (id: string) => {
    const response = await neighborhoodsService.show(id);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const neighborhoodsListSlice = createSlice({
  name: 'neighborhoods-list',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setStatusStore: (state, action: PayloadAction<IServiceRequestStatus>) => {
      state.crud.create.status = action.payload;
    },
    setStatusUpdate: (state, action: PayloadAction<IServiceRequestStatus>) => {
      state.crud.update.status = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Start List Action */
      .addCase(neighborhoodsServiceThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(neighborhoodsServiceThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data;
      })
      .addCase(neighborhoodsServiceThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.crud.create.data = action.payload as object;
      })
      /** End List Action */
      /** Start Store Action */
      .addCase(neighborhoodsStoreThunk.pending, (state) => {
        state.crud.create.status = 'loading';
      })
      .addCase(neighborhoodsStoreThunk.fulfilled, (state, action) => {
        state.crud.create.status = 'success';
        state.crud.create.data = action.payload.data;
      })
      .addCase(neighborhoodsStoreThunk.rejected, (state, action) => {
        state.crud.create.status = 'failed';
        state.crud.create.data = action.payload as object;
      })
      /** End Store Action */
      /** Start Update Action */
      .addCase(neighborhoodsUpdateThunk.pending, (state) => {
        state.crud.update.status = 'loading';
      })
      .addCase(neighborhoodsUpdateThunk.fulfilled, (state, action) => {
        state.crud.update.status = 'success';
        state.crud.update.data = action.payload.data;
      })
      .addCase(neighborhoodsUpdateThunk.rejected, (state, action) => {
        state.crud.update.status = 'failed';
        state.crud.update.data = action.payload as object;
      })
      /** End Update Action */
      /** Start Delete Action */
      .addCase(neighborhoodsDeleteThunk.pending, (state) => {
        state.crud.delete.status = 'loading';
      })
      .addCase(neighborhoodsDeleteThunk.fulfilled, (state, action) => {
        state.crud.delete.status = 'success';
        state.crud.delete.data = action.payload.data;
      })
      .addCase(neighborhoodsDeleteThunk.rejected, (state, action) => {
        state.crud.delete.status = 'failed';
        state.crud.delete.data = action.payload as object;
      })
      /** End Delete Action */
      /** Start Show Action */
      .addCase(neighborhoodsShowThunk.pending, (state) => {
        state.crud.read.status = 'loading';
      })
      .addCase(neighborhoodsShowThunk.fulfilled, (state, action) => {
        state.crud.read.status = 'success';
        state.crud.read.data = action.payload.data;
      })
      .addCase(neighborhoodsShowThunk.rejected, (state, action) => {
        state.crud.read.status = 'failed';
        state.crud.read.data = action.payload as object;
      });
  },
});

export const { setStatusStore, setStatusUpdate } = neighborhoodsListSlice.actions;

export const selectNeighborhoodsListReducer = (state: RootState) => state.neighborhoodsListReducer;

export default neighborhoodsListSlice.reducer;
