import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { employeesService } from '../../../services/employees';
import { RootState } from '../../../stores';

import { 
  IServiceRequest, 
  IServiceError,
  IEmployeeDataSearchResult
} from '../../../types';

export interface IEmployeeSearchServiceRequest extends IServiceRequest {
  data?: IEmployeeDataSearchResult | IServiceError;
}

const initialState: IEmployeeSearchServiceRequest = {
  name: 'employeesSearchReducer',
  status: 'idle',
};

export const employeesSearchThunk = createAsyncThunk(
  'employees/search',
  async (search: string) => {
    const response = await employeesService.search(search);
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const employeesSearchSlice = createSlice({
  name: 'employeesSearchReducer',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(employeesSearchThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(employeesSearchThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data as IEmployeeDataSearchResult;
      })
      .addCase(employeesSearchThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as IServiceError;
      });
  },
});

export const selectEmployeesSearchReducer = (state: RootState) => state.employeesSearchReducer;

export default employeesSearchSlice.reducer;
