import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { ownersService } from '../../../services/owners';
import { RootState } from '../../../stores';

import { IServiceRequest, IOwnersServiceThunk } from '../../../types';

const initialState: IServiceRequest = {
  name: 'ownersListReducer',
  status: 'idle',
};

export const ownersServiceThunk = createAsyncThunk(
  'owners/list',
  async ({ page }: IOwnersServiceThunk) => {
    const response = await ownersService.list({ page });
    // The value we return becomes the `fulfilled` action payload

    return response;
  }
);

export const ownersListSlice = createSlice({
  name: 'owners-list',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      /** Access token */
      .addCase(ownersServiceThunk.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(ownersServiceThunk.fulfilled, (state, action) => {
        state.status = 'success';
        state.data = action.payload.data;
      })
      .addCase(ownersServiceThunk.rejected, (state, action) => {
        state.status = 'failed';
        state.data = action.payload as object;
      });
  },
});

export const selectOwnersListReducer = (state: RootState) => state.ownersListReducer;

export default ownersListSlice.reducer;
